services:
  - type: web
    name: appian-flask
    env: python
    plan: free
    buildCommand: pip install -r flask/requirements.txt
    startCommand: gunicorn app:app
    workingDir: flask
    autoDeploy: true
